### ISSUE TITLE
nothing gets generated out of some gpx files

### ISSUE THREAD

**Issue by curiouspl2** [anoved/gpxtruder#31]
no idea why some gpx files are not rendered. 
here are some examples : 
 http://83.15.83.106/curious/gps/chojnik/fresh.gpx
http://83.15.83.106/curious/gps/Korenov_2010_12/out.gpx

**Comment by anoved** [comment]
Hi! Thanks for the report and examples. Some background:

GPX files may contain a mixture of waypoints (`<wpt>`), tracks (`<trk>`), and routes (`<rte>`). See https://en.wikipedia.org/wiki/GPS_Exchange_Format#Data_types for a description of the differences.

GPXtruder works with the first _track_ it finds in the selected GPX file. As it turns out, the first `<trk>` element in `out.gpx` is empty - it contains no points. Likewise, the first `<trk>` element in `fresh.gpx` contains only a single point, which GPXtruder isn't able to present as a path. (Note that tracks can, in turn, contain multiple _segments_ - and again, GPXtruder only deals with the first segment it finds.)

I _will_ try to improve error checking and descriptive text to clarify what's happening in cases like these.

I _don't_ think I will add an interface to select which track or segment to render. Instead, I suggest using other software to simplify or select the desired track before giving it to GPXtruder.

For example, you can use [GPSBabel](http://www.gpsbabel.org/) to delete empty tracks and consolidate the rest into a single track segment using a [track filter](http://www.gpsbabel.org/htmldoc-development/filter_track.html) like this:

```
gpsbabel -t -i gpx -f out.gpx -x track,pack -o gpx -F out-packed.gpx
```

The `out-packed.gpx` result is compatible with GPXtruder and looks like this with default settings:

![packed](https://cloud.githubusercontent.com/assets/317994/5889850/28c0efb0-a40a-11e4-94a9-975e3092d0d5.png)

(Some other sort of editing may be required if just packing tracks together includes stray points that should be discarded.)

**Comment by curiouspl2** [comment]
thanks :) i've tried various software and programs like gpsprune allow me to consolidate track like you did describe :) 

This solves the problem :)
