### ISSUE TITLE
[feature request] map elevation base

### ISSUE THREAD

**Issue by curiouspl2** [anoved/gpxtruder#32]
it would be great if one could generate also map elevation model. 

this can be done in several options : 
-integrated - map underneath route profile merged with route profile. they would get different exxageration rates though 

-interlocking - map underneath route profile as separate file, with a groove in place where route profile can be fitted (this way one can print  route profile in different colour)
route profile would go all the way to the bottom of the map (+small adjustable base like 0.2mm) 

-on-top - map underneath route profile without any groove, but route profile 'offseted' to map top .
this needs to be printed with support, but allows using single map for several route profiles.

**Comment by anoved** [comment]
Agreed! This is actually the goal I had in mind when I began making GPXtruder.

Due to a variety of projects competing for my attention, I do not plan to work on this anytime soon. Integration with a suitable source of elevation data is a key challenge.

However, it can be done manually!

You can model a region in the fashion of [Shapespeare's landscapes](http://www.thingiverse.com/thing:581851) and produce a matching scale route model through careful use of GPXtruder's settings (especially the projection, region, and max dimensions). The landscape and the route can then be combined in the ways you suggest using Blender or other 3D software.

It is on my to-do list to print an example and write a tutorial, which I will post here on GPXtruder's github page.

**Comment by anoved** [comment]
Spent this afternoon working through a sample by hand using [QGIS](http://qgis.org). Started with a GPX file of a route; retrieved SRTM 1-arc sec digital elevation tile of containing region from [USGS Earth Explorer](http://earthexplorer.usgs.gov/), and fiddled around with getting them into matching projections, extents, etc. The purple path in the image below is the route generated with GPXtruder and the matching green landscape is derived from the elevation data.

![terrain-route-screenshot](https://cloud.githubusercontent.com/assets/317994/6099762/82d0d7f6-afcf-11e4-8bf1-29a5df431e4c.png)

Definitely not going to build this _in_ to GPXtruder, but now that I've proven the process I know I can document and probably make a few small tweaks that make it easier.

**Comment by anoved** [comment]
Here is a photo of a printed version of the model shown in the screenshot above.
![photo feb 09 12 17 33 am](https://cloud.githubusercontent.com/assets/317994/6191105/f586294c-b374-11e4-9b86-f6c90c33b0f3.jpg)

**Comment by anoved** [comment]
Example of an interlocking route and landscape ([Whiteface Vertical K](http://www.thingiverse.com/thing:930875)): ![interlocking](https://cloud.githubusercontent.com/assets/317994/8894193/72bf5a60-337b-11e5-977c-ef1cdc5e553c.jpg)

**Comment by anoved** [comment]
Example of an on-top (draped) route and landscape ([Forest Frolic 7k](http://www.thingiverse.com/thing:930878)):
![ontop](https://cloud.githubusercontent.com/assets/317994/8894204/b92bd438-337b-11e5-8a0c-193473d0d69a.jpg)

**Comment by anoved** [comment]
The route models in these examples were made with GPXtruder. The landscapes were made with [phstl](https://github.com/anoved/phstl) from clipped GeoTIFF SRTM heightmap images prepared with QGIS. They were combined (via various boolean operations) via Meshmixer and/or Blender.

This process is far from automatic but is definitely doable.
